services:
  reverse-proxy:
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - source: ssl_certificate
        target: /etc/ssl/bde-grimm.com.pem
      - source: ssl_private_key
        target: /etc/ssl/bde-grimm.com.key

secrets:
  ssl_certificate:
    file: ./bde-grimm.com.pem
  ssl_private_key:
    file: ./bde-grimm.com.key
